spring:
  application:
    name: video-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    servelet:
      max-file-size: 2GB
      max-request-size: 2GB

    server:
      port: 8082

    aws:
      access-key: ${AWS_ACCESS_KEY:your-access-key}
      secret-key: ${AWS_SECRET_KEY:your-secret-key}
      region: ${AWS_REGION:ap-south-1}
      s3:
        bucket-name: ${AWS_BUCKET_NAME:abcdbucket}

    management:
      endpoints:
        web:
          exposure:
            include: health,info